"""2fa: coluna totp_recovery (codigos de recuperacao hash)

Revision ID: 0a6769eb496e
Revises: 992f8e416166
Create Date: 2026-07-01 12:11:28.442702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6769eb496e'
down_revision = '992f8e416166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_recovery', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('totp_recovery')

    # ### end Alembic commands ###
