"""agenda: disponibilidade do profissional + bloqueios

Revision ID: 11795b467b06
Revises: 85145a1b8b52
Create Date: 2026-06-17 16:41:33.369225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11795b467b06'
down_revision = '85145a1b8b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=120), nullable=True),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bloqueios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bloqueios_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bloqueios_inicio'), ['inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_bloqueios_profissional_id'), ['profissional_id'], unique=False)

    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_atendimento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hora_inicio', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hora_fim', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('intervalo_inicio', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('intervalo_fim', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_column('intervalo_fim')
        batch_op.drop_column('intervalo_inicio')
        batch_op.drop_column('hora_fim')
        batch_op.drop_column('hora_inicio')
        batch_op.drop_column('dias_atendimento')

    with op.batch_alter_table('bloqueios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bloqueios_profissional_id'))
        batch_op.drop_index(batch_op.f('ix_bloqueios_inicio'))
        batch_op.drop_index(batch_op.f('ix_bloqueios_clinica_id'))

    op.drop_table('bloqueios')
    # ### end Alembic commands ###
