"""exames (anexos do atendimento)

Revision ID: 26da7b715803
Revises: 9f76135ea7b8
Create Date: 2026-06-06 07:55:35.031223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26da7b715803'
down_revision = '9f76135ea7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=200), nullable=True),
    sa.Column('arquivo_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exames_atendimento_id'), ['atendimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_paciente_id'), ['paciente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exames_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_exames_atendimento_id'))

    op.drop_table('exames')
    # ### end Alembic commands ###
