"""multi-tenant fase 1: clinica_id NOT NULL

Revision ID: 43ccb0b2b912
Revises: 812bc4e0a35a
Create Date: 2026-06-08 13:27:05.833419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ccb0b2b912'
down_revision = '812bc4e0a35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('procedimentos', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('procedimentos', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
