"""white-label: tema da clinica

Revision ID: 4cebbbf67a2d
Revises: e5bb6ff4217f
Create Date: 2026-06-09 18:54:35.558515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cebbbf67a2d'
down_revision = 'e5bb6ff4217f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tema', sa.String(length=20), nullable=False,
                                      server_default='teal'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinicas', schema=None) as batch_op:
        batch_op.drop_column('tema')

    # ### end Alembic commands ###
