"""config fiscal clinica (NFS-e)

Revision ID: 50e9db1331c8
Revises: 6260b527ebb8
Create Date: 2026-06-23 18:25:51.502488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e9db1331c8'
down_revision = '6260b527ebb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_fiscal_clinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('gateway_empresa_id', sa.String(length=40), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('razao_social', sa.String(length=160), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=30), nullable=True),
    sa.Column('codigo_municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('regime_tributario', sa.String(length=12), nullable=True),
    sa.Column('aliquota_iss', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('codigo_servico', sa.String(length=20), nullable=True),
    sa.Column('cnae', sa.String(length=10), nullable=True),
    sa.Column('iss_retido_padrao', sa.Boolean(), nullable=False),
    sa.Column('certificado_validade', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', name='uq_config_fiscal_clinica')
    )
    with op.batch_alter_table('config_fiscal_clinica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_fiscal_clinica_clinica_id'), ['clinica_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_fiscal_clinica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_fiscal_clinica_clinica_id'))

    op.drop_table('config_fiscal_clinica')
    # ### end Alembic commands ###
