"""whatsapp: contas, contatos, mensagens

Revision ID: 6260b527ebb8
Revises: fb70ccad47bf
Create Date: 2026-06-23 10:44:28.914243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6260b527ebb8'
down_revision = 'fb70ccad47bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.String(length=40), nullable=True),
    sa.Column('waba_id', sa.String(length=40), nullable=True),
    sa.Column('display_phone', sa.String(length=20), nullable=True),
    sa.Column('nome_exibicao', sa.String(length=120), nullable=True),
    sa.Column('token_cifrado', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', name='uq_whatsapp_conta_clinica')
    )
    with op.batch_alter_table('whatsapp_contas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_contas_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_contas_phone_number_id'), ['phone_number_id'], unique=True)

    op.create_table('whatsapp_contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('wa_id', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('nao_lidas', sa.Integer(), nullable=False),
    sa.Column('ultima_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'wa_id', name='uq_whatsapp_contato')
    )
    with op.batch_alter_table('whatsapp_contatos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_contatos_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_contatos_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_contatos_ultima_em'), ['ultima_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_contatos_wa_id'), ['wa_id'], unique=False)

    op.create_table('whatsapp_mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('contato_id', sa.Integer(), nullable=False),
    sa.Column('direcao', sa.String(length=3), nullable=False),
    sa.Column('wa_message_id', sa.String(length=80), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['contato_id'], ['whatsapp_contatos.id'], ),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_mensagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_mensagens_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_mensagens_contato_id'), ['contato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_mensagens_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_mensagens_wa_message_id'), ['wa_message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_mensagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_mensagens_wa_message_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_mensagens_criado_em'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_mensagens_contato_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_mensagens_clinica_id'))

    op.drop_table('whatsapp_mensagens')
    with op.batch_alter_table('whatsapp_contatos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_contatos_wa_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_contatos_ultima_em'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_contatos_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_contatos_clinica_id'))

    op.drop_table('whatsapp_contatos')
    with op.batch_alter_table('whatsapp_contas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_contas_phone_number_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_contas_clinica_id'))

    op.drop_table('whatsapp_contas')
    # ### end Alembic commands ###
