"""crm: atendimento.retorno_em

Revision ID: 7cfccd5be9dc
Revises: d252a3418946
Create Date: 2026-06-05 20:17:38.353224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfccd5be9dc'
down_revision = 'd252a3418946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retorno_em', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_column('retorno_em')

    # ### end Alembic commands ###
