"""multi-tenant fase 0: clinicas + clinica_id

Revision ID: 812bc4e0a35a
Revises: b8df33a472c4
Create Date: 2026-06-08 11:36:44.294963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812bc4e0a35a'
down_revision = 'b8df33a472c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinica_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agendamentos_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_foreign_key('fk_clinica', 'clinicas', ['clinica_id'], ['id'])

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinica_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_atendimentos_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_foreign_key('fk_clinica', 'clinicas', ['clinica_id'], ['id'])

    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinica_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_exames_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_foreign_key('fk_clinica', 'clinicas', ['clinica_id'], ['id'])

    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinica_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lancamentos_financeiros_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_foreign_key('fk_clinica', 'clinicas', ['clinica_id'], ['id'])

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinica_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pacientes_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_foreign_key('fk_clinica', 'clinicas', ['clinica_id'], ['id'])

    with op.batch_alter_table('procedimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinica_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_procedimentos_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_foreign_key('fk_clinica', 'clinicas', ['clinica_id'], ['id'])

    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinica_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_profissionais_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_foreign_key('fk_clinica', 'clinicas', ['clinica_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinica_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_foreign_key('fk_clinica', 'clinicas', ['clinica_id'], ['id'])

    # ### end Alembic commands ###

    # --- Backfill: clínica default + vincula todas as linhas já existentes.
    # Fase 0 não quebra nada: a instância vira "clínica 1" e tudo aponta p/ ela.
    clinicas = sa.table(
        "clinicas",
        sa.column("id", sa.Integer),
        sa.column("nome", sa.String),
        sa.column("slug", sa.String),
        sa.column("ativo", sa.Boolean),
    )
    op.bulk_insert(clinicas, [
        {"id": 1, "nome": "Clínica Nous", "slug": "nous", "ativo": True},
    ])
    for tabela in ("usuarios", "profissionais", "pacientes", "agendamentos",
                   "atendimentos", "lancamentos_financeiros", "procedimentos",
                   "exames"):
        op.execute(f"UPDATE {tabela} SET clinica_id = 1 WHERE clinica_id IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clinica', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_usuarios_clinica_id'))
        batch_op.drop_column('clinica_id')

    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clinica', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_profissionais_clinica_id'))
        batch_op.drop_column('clinica_id')

    with op.batch_alter_table('procedimentos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clinica', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_procedimentos_clinica_id'))
        batch_op.drop_column('clinica_id')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clinica', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pacientes_clinica_id'))
        batch_op.drop_column('clinica_id')

    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clinica', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lancamentos_financeiros_clinica_id'))
        batch_op.drop_column('clinica_id')

    with op.batch_alter_table('exames', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clinica', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_exames_clinica_id'))
        batch_op.drop_column('clinica_id')

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clinica', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_atendimentos_clinica_id'))
        batch_op.drop_column('clinica_id')

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clinica', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agendamentos_clinica_id'))
        batch_op.drop_column('clinica_id')

    op.drop_table('clinicas')
    # ### end Alembic commands ###
