"""paciente: campo origem (como conheceu a clinica)

Revision ID: 85145a1b8b52
Revises: f78e582ded10
Create Date: 2026-06-12 10:41:18.812925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85145a1b8b52'
down_revision = 'f78e582ded10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('origem')

    # ### end Alembic commands ###
