"""precos por convenio

Revision ID: 91024b7c05db
Revises: 26da7b715803
Create Date: 2026-06-06 08:03:15.073689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91024b7c05db'
down_revision = '26da7b715803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precos_convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedimento_id', sa.Integer(), nullable=False),
    sa.Column('convenio', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['procedimento_id'], ['procedimentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procedimento_id', 'convenio', name='uq_preco_proc_conv')
    )
    with op.batch_alter_table('precos_convenio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precos_convenio_procedimento_id'), ['procedimento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precos_convenio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precos_convenio_procedimento_id'))

    op.drop_table('precos_convenio')
    # ### end Alembic commands ###
