"""hardening custo-zero: indices retorno/criado, anonimizacao paciente, lockout+2fa+ultimo_ip

Revision ID: 992f8e416166
Revises: e5adbcd7575e
Create Date: 2026-07-01 10:56:32.127420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992f8e416166'
down_revision = 'e5adbcd7575e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.create_index('ix_atend_clinica_retorno', ['clinica_id', 'retorno_em'], unique=False)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anonimizado_em', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_pac_clinica_criado', ['clinica_id', 'criado_em'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        # server_default nos NOT NULL: sem ele o ADD COLUMN falha em tabela com
        # linhas existentes no Postgres. O app sempre seta o valor depois.
        batch_op.add_column(sa.Column('tentativas_falhas', sa.Integer(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('ultimo_login_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('totp_ativado', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('totp_ativado')
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('ultimo_login_ip')
        batch_op.drop_column('bloqueado_ate')
        batch_op.drop_column('tentativas_falhas')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index('ix_pac_clinica_criado')
        batch_op.drop_column('anonimizado_em')

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_index('ix_atend_clinica_retorno')

    # ### end Alembic commands ###
