"""agendamento: checkin_em

Revision ID: 9ea3aeed7c47
Revises: 91024b7c05db
Create Date: 2026-06-08 10:21:11.576403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea3aeed7c47'
down_revision = '91024b7c05db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkin_em', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('checkin_em')

    # ### end Alembic commands ###
