"""procedimentos + itens_atendimento

Revision ID: 9f76135ea7b8
Revises: 9382154d1308
Create Date: 2026-06-06 07:26:23.117166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f76135ea7b8'
down_revision = '9382154d1308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor_padrao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('procedimento_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['procedimento_id'], ['procedimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_atendimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_atendimento_atendimento_id'), ['atendimento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_atendimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_atendimento_atendimento_id'))

    op.drop_table('itens_atendimento')
    op.drop_table('procedimentos')
    # ### end Alembic commands ###
