"""usuario: clinica_id nullable (superadmin)

Revision ID: b751d4b5ffcc
Revises: 43ccb0b2b912
Create Date: 2026-06-08 13:35:36.332041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b751d4b5ffcc'
down_revision = '43ccb0b2b912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('clinica_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
