"""agendamento: lembrete_enviado_em

Revision ID: b8df33a472c4
Revises: f5a5f0ffed87
Create Date: 2026-06-08 11:24:39.694013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8df33a472c4'
down_revision = 'f5a5f0ffed87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lembrete_enviado_em', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('lembrete_enviado_em')

    # ### end Alembic commands ###
