"""indices compostos: agenda, financeiro, atendimento (perf)

Revision ID: c17fa9789849
Revises: cfb680b7a433
Create Date: 2026-06-30 11:34:20.705445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17fa9789849'
down_revision = 'cfb680b7a433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index('ix_ag_clinica_inicio', ['clinica_id', 'inicio'], unique=False)
        batch_op.create_index('ix_ag_prof_inicio', ['profissional_id', 'inicio'], unique=False)

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.create_index('ix_atend_clinica_criado', ['clinica_id', 'criado_em'], unique=False)

    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.create_index('ix_lanc_clinica_status_tipo_pago', ['clinica_id', 'status', 'tipo', 'pago_em'], unique=False)
        batch_op.create_index('ix_lanc_clinica_status_tipo_venc', ['clinica_id', 'status', 'tipo', 'vencimento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.drop_index('ix_lanc_clinica_status_tipo_venc')
        batch_op.drop_index('ix_lanc_clinica_status_tipo_pago')

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_index('ix_atend_clinica_criado')

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index('ix_ag_prof_inicio')
        batch_op.drop_index('ix_ag_clinica_inicio')

    # ### end Alembic commands ###
