"""endereco do emitente fiscal

Revision ID: cfb680b7a433
Revises: 50e9db1331c8
Create Date: 2026-06-23 19:19:41.402734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb680b7a433'
down_revision = '50e9db1331c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_fiscal_clinica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('uf', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_fiscal_clinica', schema=None) as batch_op:
        batch_op.drop_column('cep')
        batch_op.drop_column('uf')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
