"""financeiro: lancamentos_financeiros

Revision ID: d252a3418946
Revises: d33154aa79b5
Create Date: 2026-06-05 15:38:33.685586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd252a3418946'
down_revision = 'd33154aa79b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lancamentos_financeiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('pago_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('convenio', sa.String(length=80), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamentos_financeiros_agendamento_id'), ['agendamento_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_lancamentos_financeiros_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_financeiros_pago_em'), ['pago_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_financeiros_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_financeiros_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos_financeiros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_financeiros_tipo'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_financeiros_status'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_financeiros_pago_em'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_financeiros_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_financeiros_agendamento_id'))

    op.drop_table('lancamentos_financeiros')
    # ### end Alembic commands ###
