"""schema inicial: usuarios, profissionais, pacientes, agendamentos, atendimentos, audit_logs

Revision ID: d33154aa79b5
Revises: 
Create Date: 2026-06-05 15:08:12.199675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33154aa79b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_responsavel', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=40), nullable=True),
    sa.Column('aceite_termos_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('senha_atualizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('recurso_tipo', sa.String(length=40), nullable=True),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('convenio', sa.String(length=80), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_nome_completo'), ['nome_completo'], unique=False)

    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('registro_conselho', sa.String(length=40), nullable=True),
    sa.Column('cor_agenda', sa.String(length=7), nullable=True),
    sa.Column('duracao_padrao_min', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('convenio', sa.String(length=80), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamentos_inicio'), ['inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_profissional_id'), ['profissional_id'], unique=False)

    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('queixa', sa.Text(), nullable=True),
    sa.Column('evolucao', sa.Text(), nullable=True),
    sa.Column('prescricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agendamento_id')
    )
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atendimentos_paciente_id'), ['paciente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atendimentos_paciente_id'))

    op.drop_table('atendimentos')
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamentos_profissional_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_inicio'))

    op.drop_table('agendamentos')
    op.drop_table('profissionais')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_nome_completo'))

    op.drop_table('pacientes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_criado_em'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_acao'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
