"""white-label v2: logo e cor_primaria da clinica

Revision ID: d982f26a3254
Revises: 4cebbbf67a2d
Create Date: 2026-06-09 19:10:06.606039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd982f26a3254'
down_revision = '4cebbbf67a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_primaria', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('logo_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_mime', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinicas', schema=None) as batch_op:
        batch_op.drop_column('logo_mime')
        batch_op.drop_column('logo_key')
        batch_op.drop_column('cor_primaria')

    # ### end Alembic commands ###
