"""fechamentos_caixa (fechamento de caixa diario)

Revision ID: e5adbcd7575e
Revises: f91b5c54b1ac
Create Date: 2026-06-30 13:25:40.821563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5adbcd7575e'
down_revision = 'f91b5c54b1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fechamentos_caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('esperado_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contado_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('divergencia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('fechado_por_id', sa.Integer(), nullable=True),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['fechado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'dia', name='uq_fechamento_dia')
    )
    with op.batch_alter_table('fechamentos_caixa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fechamentos_caixa_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fechamentos_caixa_dia'), ['dia'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fechamentos_caixa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fechamentos_caixa_dia'))
        batch_op.drop_index(batch_op.f('ix_fechamentos_caixa_clinica_id'))

    op.drop_table('fechamentos_caixa')
    # ### end Alembic commands ###
