"""convenios (master), sala em profissional e agendamento

Revision ID: e5bb6ff4217f
Revises: b751d4b5ffcc
Create Date: 2026-06-08 15:54:39.828316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bb6ff4217f'
down_revision = 'b751d4b5ffcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'nome', name='uq_convenio_clinica_nome')
    )
    with op.batch_alter_table('convenios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convenios_clinica_id'), ['clinica_id'], unique=False)

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sala', sa.String(length=40), nullable=True))

    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sala', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_column('sala')

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('sala')

    with op.batch_alter_table('convenios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convenios_clinica_id'))

    op.drop_table('convenios')
    # ### end Alembic commands ###
