"""profissional: comissao_percent

Revision ID: f5a5f0ffed87
Revises: 9ea3aeed7c47
Create Date: 2026-06-08 10:43:33.037513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a5f0ffed87'
down_revision = '9ea3aeed7c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comissao_percent', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_column('comissao_percent')

    # ### end Alembic commands ###
