"""atendimento: campos de atestado (dias, cid)

Revision ID: f78e582ded10
Revises: d982f26a3254
Create Date: 2026-06-09 21:37:08.207771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78e582ded10'
down_revision = 'd982f26a3254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atestado_dias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atestado_cid', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_column('atestado_cid')
        batch_op.drop_column('atestado_dias')

    # ### end Alembic commands ###
