"""movimentos_bancarios (conciliacao OFX)

Revision ID: f91b5c54b1ac
Revises: c17fa9789849
Create Date: 2026-06-30 12:20:28.792849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91b5c54b1ac'
down_revision = 'c17fa9789849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentos_bancarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=8), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('fitid', sa.String(length=80), nullable=True),
    sa.Column('conta', sa.String(length=40), nullable=True),
    sa.Column('banco', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=True),
    sa.Column('importado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('importado_por_id', sa.Integer(), nullable=True),
    sa.Column('conciliado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conciliado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['conciliado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['importado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos_financeiros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'conta', 'fitid', name='uq_mov_fitid')
    )
    with op.batch_alter_table('movimentos_bancarios', schema=None) as batch_op:
        batch_op.create_index('ix_mov_clinica_status_data', ['clinica_id', 'status', 'data'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_bancarios_clinica_id'), ['clinica_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_bancarios_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_bancarios_lancamento_id'), ['lancamento_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_movimentos_bancarios_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentos_bancarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_bancarios_status'))
        batch_op.drop_index(batch_op.f('ix_movimentos_bancarios_lancamento_id'))
        batch_op.drop_index(batch_op.f('ix_movimentos_bancarios_data'))
        batch_op.drop_index(batch_op.f('ix_movimentos_bancarios_clinica_id'))
        batch_op.drop_index('ix_mov_clinica_status_data')

    op.drop_table('movimentos_bancarios')
    # ### end Alembic commands ###
