"""salas: cadastro de salas/consultorios

Revision ID: fb70ccad47bf
Revises: 11795b467b06
Create Date: 2026-06-17 20:31:38.738793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb70ccad47bf'
down_revision = '11795b467b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'nome', name='uq_sala_clinica_nome')
    )
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salas_clinica_id'), ['clinica_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salas_clinica_id'))

    op.drop_table('salas')
    # ### end Alembic commands ###
